### ISSUE TITLE
Node REPL ends up in unusable state when node process dies

### ISSUE THREAD

**Issue by thheller** [thheller/shadow-cljs#370]
`(js/process.exit 1)` or an uncaught exception in async will cause the node process to exit but REPL session is not cleaned up properly.

**Comment by loganpowell** [comment]
Hi @thheller ! Is this good news?

**Comment by thheller** [comment]
It should be fixed yes. I guess thats good news?

**Comment by loganpowell** [comment]
You have indeed! You are incredible man. Thank you!

**Comment by loganpowell** [comment]
OMG, this is saving me so much time dude. You have no idea.

**Comment by loganpowell** [comment]
I think I might have found a way to break it: if you put `nil` on a `chan` you get:
```
C:\Users\Surface\Projects\clojure\cljs\census-geojson\.shadow-cljs\builds\node-repl\dev\out\cljs-runtime\cljs\core\async\impl\channels.cljs:46
    (assert (not (nil? val)) "Can't put nil on a channel")
    ^
Error: Assert failed: Can't put nil on a channel
(not (nil? val))
    at cljs.core.async.impl.channels.ManyToManyChannel.cljs$core$async$impl$protocols$WritePort$put_BANG_$arity$3 (C:\Users\Surface\Projects\clojure\cljs\census-geojson\.shadow-cljs\builds\node-repl\dev\out\cljs-runtime\cljs\core\async\impl\channels.cljs:46:5)
    at Object.cljs$core$async$impl$protocols$put_BANG_ [as put_BANG_] (C:\Users\Surface\Projects\clojure\cljs\census-geojson\.shadow-cljs\builds\node-repl\dev\out\cljs-runtime\cljs\core\async\impl\protocols.cljs:17:10)
    at Function.cljs.core.async.put_BANG_.cljs$core$IFn$_invoke$arity$4 (C:\Users\Surface\Projects\clojure\cljs\census-geojson\.shadow-cljs\builds\node-repl\dev\out\cljs-runtime\cljs\core\async.cljs:126:20)
    at Function.cljs.core.async.put_BANG_.cljs$core$IFn$_invok
```
Then if I try to eval any other function... old faithful:

```
CompilerException java.lang.RuntimeException: Unable to resolve symbol: into in this context, compiling:(null:1:1) 
```

**Comment by thheller** [comment]
It should be working properly in `2.6.2`.

**Comment by loganpowell** [comment]
Man, you are fast.

**Comment by loganpowell** [comment]
```
λ shadow-cljs clj-repl
shadow-cljs - config: C:\Users\Surface\Projects\clojure\cljs\census-geojson\shadow-cljs.edn  cli version: 2.6.2  node: v8.11.3
shadow-cljs - starting ...
Aug 22, 2018 9:26:29 AM org.xnio.Xnio <clinit>
INFO: XNIO version 3.3.8.Final
Aug 22, 2018 9:26:29 AM org.xnio.nio.NioXnio <clinit>
INFO: XNIO NIO Implementation Version 3.3.8.Final
shadow-cljs - server version: 2.6.2
shadow-cljs - server running at http://localhost:9630
shadow-cljs - socket REPL running on port 63347
shadow-cljs - nREPL server started on port 3333
shadow-cljs - REPL - see (help)
To quit, type: :repl/quit
[1:0]~shadow.user=> shutting down ...
shutting down ...
Exception in thread "async-dispatch-8" Exception in thread "async-dispatch-3" Exception in thread "async-dispatch-4" java.lang.Error: java.net.SocketException: Socket closed
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.net.SocketException: Socket closed
        at java.net.SocketOutputStream.socketWrite(Unknown Source)
        at java.net.SocketOutputStream.write(Unknown Source)
        at java.io.BufferedOutputStream.flushBuffer(Unknown Source)
        at java.io.BufferedOutputStream.flush(Unknown Source)
        at nrepl.transport$bencode$fn__862.invoke(transport.clj:100)
        at nrepl.transport.FnTransport.send(transport.clj:25)
        at nrepl.middleware.pr_values$pr_values$fn$reify__1237.send(pr_values.clj:25)
        at shadow.cljs.devtools.server.nrepl04$send.invokeStatic(nrepl04.clj:33)
        at shadow.cljs.devtools.server.nrepl04$send.invoke(nrepl04.clj:20)
        at shadow.cljs.devtools.server.nrepl04$worker_exit.invokeStatic(nrepl04.clj:148)
        at shadow.cljs.devtools.server.nrepl04$worker_exit.invoke(nrepl04.clj:146)
        at shadow.cljs.devtools.server.nrepl04$cljs_select$fn__1601$fn__1603.invoke(nrepl04.clj:165)
        at shadow.cljs.devtools.api$nrepl_select$fn__15906$state_machine__6255__auto____15923$fn__15925.invoke(api.clj:383)
        at shadow.cljs.devtools.api$nrepl_select$fn__15906$state_machine__6255__auto____15923.invoke(api.clj:376)
        at clojure.core.async.impl.ioc_macros$run_state_machine.invokeStatic(ioc_macros.clj:973)
        at clojure.core.async.impl.ioc_macros$run_state_machine.invoke(ioc_macros.clj:972)
        at clojure.core.async.impl.ioc_macros$run_state_machine_wrapped.invokeStatic(ioc_macros.clj:977)
        at clojure.core.async.impl.ioc_macros$run_state_machine_wrapped.invoke(ioc_macros.clj:975)
        at clojure.core.async$ioc_alts_BANG_$fn__6470.invoke(async.clj:383)
        at clojure.core.async$do_alts$fn__6410$fn__6413.invoke(async.clj:252)
        at clojure.core.async.impl.channels.ManyToManyChannel$fn__1949.invoke(channels.clj:265)
        at clojure.lang.AFn.run(AFn.java:22)
        ... 3 more
```

**Comment by loganpowell** [comment]
Sorry for bothering with this, but still having issues with `nil`s accidentally making their way into a `chan` breaking the Node REPL. Just thought you'd be interested. Still <3 Shadow!

**Comment by thheller** [comment]
I'm confused? The `:repl/quit` exception is not related to `nil`.

The original issue was about the nrepl session not getting cleaned properly when the node process crashes. That is fixed as far as I can tell. It doesn't prevent you from crashing the process though? Not sure that it should?

**Comment by loganpowell** [comment]
Sorry for the confusion, There are two separate issues, but I thought they might be related. My REPL session still gets cut off when a `nil` makes it into a `chan`, but also, when shutting down (restarting) the remote REPL session, I get that stack trace of the socket disconnecting...

**Comment by thheller** [comment]
If you run `shadow-cljs clj-repl` while no server is running it will implicitly become the server as well. This means that the server will be killed if you exit the `clj-repl` which means everything else also gets killed.

If you want to avoid this run `shadow-cljs server` completely separately and leave that running.

**Comment by loganpowell** [comment]
So I tried this and got the same behavior:

```
=> #object[cljs.core.async.impl.channels.ManyToManyChannel]

C:\Users\Surface\Projects\clojure\cljs\census-geojson\.shadow-cljs\builds\node-repl\dev\out\cljs-runtime\cljs\core\async\impl\channels.cljs:46
    (assert (not (nil? val)) "Can't put nil on a channel")
    ^
Error: Assert failed: Can't put nil on a channel
(not (nil? val))
    at cljs.core.async.impl.channels.ManyToManyChannel.cljs$core$async$impl$protocols$WritePort$put_BANG_$arity$3 (C:\Users\Surface\Projects\clojure\cljs\census-geojson\.shadow-cljs\builds\node-repl\dev\out\cljs-runtime\cljs\core\async\impl\channels.cljs:46:5)
    at Object.cljs$core$async$impl$ioc_helpers$put_BANG_ [as put_BANG_] (C:\Users\Surface\Projects\clojure\cljs\census-geojson\.shadow-cljs\builds\node-repl\dev\out\cljs-runtime\cljs\core\async\impl\ioc_helpers.cljs:54:15)
    at C:\Users\Surface\Projects\clojure\cljs\census-geojson\.shadow-cljs\builds\node-repl\dev\out\cljs-runtime\utils\core.cljs:193:33
    at C:\Users\Surface\Projects\clojure\cljs\census-geojson\.shadow-cljs\builds\node-repl\dev\out\cljs-runtime\utils\core.cljs:19
The REPL worker has stopped.
=> :cljs/quit
```

And in the `shadow-cljs server` (terminal):

```
λ shadow-cljs server
shadow-cljs - config: C:\Users\Surface\Projects\clojure\cljs\census-geojson\shadow-cljs.edn  cli version: 2.6.10  node: v8.11.4
shadow-cljs - starting ...
Sep 28, 2018 4:14:55 PM org.xnio.Xnio <clinit>
INFO: XNIO version 3.3.8.Final
Sep 28, 2018 4:14:55 PM org.xnio.nio.NioXnio <clinit>
INFO: XNIO NIO Implementation Version 3.3.8.Final
shadow-cljs - server version: 2.6.10
shadow-cljs - server running at http://localhost:9630
shadow-cljs - socket REPL running on port 61390
shadow-cljs - nREPL server started on port 3333
[2018-09-28 16:15:47.275 - INFO] :shadow.cljs.devtools.server.repl-impl/node-repl-exit - {:code 1}

```

**Comment by loganpowell** [comment]
Just tried the same thing `shadow-cljs server` in the terminal in IDEA and had the same results

**Comment by loganpowell** [comment]
New stacktrace (first time I've seen it when getting kicked out):
```
C:\Users\Surface\Projects\clojure\cljs\census-geojson>shadow-cljs server
shadow-cljs - config: C:\Users\Surface\Projects\clojure\cljs\census-geojson\shadow-cljs.edn  cli version: 2.6.10  node: v8.11.4
shadow-cljs - starting ...
Sep 28, 2018 4:40:28 PM org.xnio.Xnio <clinit>
INFO: XNIO version 3.3.8.Final
Sep 28, 2018 4:40:28 PM org.xnio.nio.NioXnio <clinit>
INFO: XNIO NIO Implementation Version 3.3.8.Final
shadow-cljs - server version: 2.6.10
shadow-cljs - server running at http://localhost:9630
shadow-cljs - socket REPL running on port 49814
shadow-cljs - nREPL server started on port 3333
[2018-09-28 16:41:26.403 - INFO] :shadow.cljs.devtools.server.repl-impl/node-repl-exit - {:code 1}
Exception in thread "async-dispatch-2" java.lang.Error: java.net.SocketException: Socket closed
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.net.SocketException: Socket closed
        at java.net.SocketOutputStream.socketWrite(Unknown Source)
        at java.net.SocketOutputStream.write(Unknown Source)
        at java.io.BufferedOutputStream.flushBuffer(Unknown Source)
        at java.io.BufferedOutputStream.flush(Unknown Source)
        at nrepl.transport$bencode$fn__862.invoke(transport.clj:100)
        at nrepl.transport.FnTransport.send(transport.clj:25)
        at shadow.cljs.devtools.server.nrepl04$send.invokeStatic(nrepl04.clj:33)
        at shadow.cljs.devtools.server.nrepl04$send.invoke(nrepl04.clj:20)
        at shadow.cljs.devtools.server.nrepl04$worker_exit.invokeStatic(nrepl04.clj:148)
        at shadow.cljs.devtools.server.nrepl04$worker_exit.invoke(nrepl04.clj:146)
        at shadow.cljs.devtools.server.nrepl04$cljs_select$fn__1601$fn__1603.invoke(nrepl04.clj:165)
        at shadow.cljs.devtools.api$nrepl_select$fn__15552$state_machine__6333__auto____15569$fn__15571.invoke(api.clj:380)
        at shadow.cljs.devtools.api$nrepl_select$fn__15552$state_machine__6333__auto____15569.invoke(api.clj:373)
        at clojure.core.async.impl.ioc_macros$run_state_machine.invokeStatic(ioc_macros.clj:973)
        at clojure.core.async.impl.ioc_macros$run_state_machine.invoke(ioc_macros.clj:972)
        at clojure.core.async.impl.ioc_macros$run_state_machine_wrapped.invokeStatic(ioc_macros.clj:977)
        at clojure.core.async.impl.ioc_macros$run_state_machine_wrapped.invoke(ioc_macros.clj:975)
        at clojure.core.async$ioc_alts_BANG_$fn__6548.invoke(async.clj:383)
        at clojure.core.async$do_alts$fn__6488$fn__6491.invoke(async.clj:252)
        at clojure.core.async.impl.channels.ManyToManyChannel$fn__2027.invoke(channels.clj:265)
        at clojure.lang.AFn.run(AFn.java:22)
        ... 3 more
```

and in the REPL:

```
=> #object[cljs.core.async.impl.channels.ManyToManyChannel]

The REPL worker has stopped.
=> :cljs/quit

```

I'm baffled

**Comment by loganpowell** [comment]
If I use `shadow-cljs clj-repl` (which usually works for me) I get a different error... sorry for bombing you with these, but I figure they would help:

terminal:

```
C:\Users\Surface\Projects\clojure\cljs\census-geojson>shadow-cljs clj-repl
shadow-cljs - config: C:\Users\Surface\Projects\clojure\cljs\census-geojson\shadow-cljs.edn  cli version: 2.6.10  node: v8.11.4
shadow-cljs - starting ...
Sep 28, 2018 4:44:11 PM org.xnio.Xnio <clinit>
INFO: XNIO version 3.3.8.Final
Sep 28, 2018 4:44:11 PM org.xnio.nio.NioXnio <clinit>
INFO: XNIO NIO Implementation Version 3.3.8.Final
shadow-cljs - server version: 2.6.10
shadow-cljs - server running at http://localhost:9630
shadow-cljs - socket REPL running on port 49878
shadow-cljs - nREPL server started on port 3333
shadow-cljs - REPL - see (help)
To quit, type: :repl/quit
[1:0]~shadow.user=> [2018-09-28 16:44:51.596 - INFO] :shadow.cljs.devtools.server.repl-impl/node-repl-exit - {:code 1}

```

REPL:

```
=> #object[cljs.core.async.impl.channels.ManyToManyChannel]
"https://api.census.gov/data/2016/acs/acs5?get=B01001_001E,NAME&B00001_001E=0:30000&in=state:03&for=state legislative district (upper chamber):*&key=6980d91653a1f78acd456d9187ed28e23ea5d4e3"


C:\Users\Surface\Projects\clojure\cljs\census-geojson\.shadow-cljs\builds\node-repl\dev\out\cljs-runtime\cljs\core\async\impl\channels.cljs:46
    (assert (not (nil? val)) "Can't put nil on a channel")
    ^
Error: Assert failed: Can't put nil on a channel
(not (nil? val))
    at cljs.core.async.impl.channels.ManyToManyChannel.cljs$core$async$impl$protocols$WritePort$put_BANG_$arity$3 (C:\Users\Surface\Projects\clojure\cljs\census-geojson\.shadow-cljs\builds\node-repl\dev\out\cljs-runtime\cljs\core\async\impl\channels.cljs:46:5)
    at Object.cljs$core$async$impl$ioc_helpers$put_BANG_ [as put_BANG_] (C:\Users\Surface\Projects\clojure\cljs\census-geojson\.shadow-cljs\builds\node-repl\dev\out\cljs-runtime\cljs\core\async\impl\ioc_helpers.cljs:54:15)
    at C:\Users\Surface\Projects\clojure\cljs\census-geojson\.shadow-cljs\builds\node-repl\dev\out\cljs-runtime\utils\core.cljs:193:33
    at C:\Users\Surface\Projects\clojure\cljs\census-geojson\.shadow-cljs\builds\node-repl\dev\out\cljs-runtime\utils\core.cljs:193:33
    at Function.utils$core$IO_ajax_GET_json_$_state_machine__16066__auto____1 [as cljs$core$IFn$_invoke$arity$1] (C:\Users\Surface\Projects\clojure\cljs\census-geojson\.shadow-cljs\builds\node-repl\dev\out\cljs-runtime\utils.core.js:531:4)
    at Object.cljs$core$async$impl$ioc_helpers$run_state_machine [as run_state_machine] (C:\Users\Surface\Projects\clojure\cljs\census-geojson\.shadow-cljs\builds\node-repl\dev\out\cljs-runtime\cljs\core\async\impl\ioc_helpers.cljs:35:3)
    at Object.cljs$core$async$impl$ioc_helpers$run_state_machine_wrapped [as run_state_machine_wrapped] (C:\Users\Surface\Projects\clojure\cljs\census-geojson\.shadow-cljs\builds\node-repl\dev\out\cljs-runtime\cljs\core\async\impl\ioc_helpers.cljs:39:6)
    at C:\Users\Surface\Projects\clojure\cljs\census-geojson\.shadow-cljs\builds\node-repl\dev\out\cljs-runtime\utils\core.cljs:193:33
    at Immediate.cljs$core$async$impl$dispatch$process_messages [as _onImmediate] (C:\Users\Surface\Projects\clojure\cljs\census-geojson\.shadow-cljs\builds\node-repl\dev\out\cljs-runtime\cljs\core\async\impl\dispatch.cljs:19:10)
    at runCallback (timers.js:810:20)

The REPL worker has stopped.
=> :cljs/quit

```

**Comment by loganpowell** [comment]
It's always when I put `nil` on a `chan`

**Comment by thheller** [comment]
Forget about putting `nil` on a channel for a second. What you have here is an uncaught Exception. In node that means the process will crash.

```
[1:1]~cljs.user=> (js/setTimeout #(throw (ex-info "boom" {})) 1)
The REPL worker has stopped.
```

Any uncaught exception will do that. The reason

```
[2:1]~cljs.user=> (throw (ex-info "boom" {}))
```
doesn't crash is that the REPL `eval` is actually wrapped in try/catch but that doesn't help when you go async. Meaning that any uncaught exception in core.async or otherwise will crash the entire node process. AFAICT that is the default behaviour for the normal CLJS node REPL as well.

You can prevent that by installing an uncaught exception handler yourself.
https://nodejs.org/api/process.html#process_event_uncaughtexception

I'm unsure whether or not shadow-cljs should do that by default.

**Comment by loganpowell** [comment]
Ah, I gotcha. So sorry. I need to handle my exceptions... I am still prototyping, but I'll do that. Thank you for your patience. I'll not be back about this error again.

**Comment by loganpowell** [comment]
Just a note for those who might find this ex-post:

https://dev.clojure.org/jira/browse/ASYNC-61

**Comment by thheller** [comment]
That is about Clojure `core.async` and not related to CLJS.

If you want to stop crashing the node-repl call

```
(js/process.on "uncaughtException" (fn [err] (prn [:uncaught err])))`
``

as the first thing in the REPL. Note that this code may actually also cause an exception which will then loop endlessly. Doing this correctly is hard ...

**Comment by loganpowell** [comment]
I can delete the comment?
